### ISSUE TITLE
Not working on 1.20.1 

### ISSUE THREAD

**Issue by andriiqx** [GabrielFJunkes/MultipleBedSpawn#32]
Spigot, 1.20.1:

[13:48:44] [Server thread/ERROR] [Minecraft]: Error occurred while enabling MultipleBedSpawn v1.10 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandMap org.bukkit.Server.getCommandMap()'
	at me.gabrielfj.multiplebedspawn.MultipleBedSpawn.onEnable(MultipleBedSpawn.java:35) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.30-universal.jar%23347!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.30-universal.jar%23347!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.30-universal.jar%23347!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:550) ~[forge-1.20.1-47.2.30-universal.jar%23347!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:463) ~[forge-1.20.1-47.2.30-universal.jar%23347!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:217) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by GabiJunkes** [comment]
Are you using spigot or paper?

**Comment by andriiqx** [comment]
> Are you using spigot or paper?

spigot

**Comment by GabiJunkes** [comment]
Fixed in [V1.11](https://github.com/GabrielFJunkes/MultipleBedSpawn/releases/tag/V1.11). If not, you can open another issue.
